# Generated by Django 4.1 on 2022-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_todomodel_duedate_todomodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="priority",
            field=models.CharField(
                choices=[("danger", "high"), ("info", "normal"), ("secondary", "low")],
                max_length=50,
            ),
        ),
    ]
